# Generated by Django 2.2.6 on 2019-10-12 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitems',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
