export const TOGGLE_COLLAPSE = "dashboard/TOGGLE_COLLAPSE";
export const FETCH_JOBITEMS = "dashboard/FETCH_JOBITEMS";
export const FETCH_JOBITEMS_SUCCESS = "dashboard/FETCH_JOBITEMS_SUCCESS";
export const FETCH_JOBITEMS_FAIL = "dashboard/FETCH_JOBITEMS_FAIL";

export const DELETE_JOBITEMS = "dashboard/DELETE_JOBITEMS";
export const DELETE_JOBITEMSSUCCESS = "dashboard/DELETE_JOBITEMSSUCCESS";

export const CREATE_JOBITEMS = "dashboard/CREATE_JOBITEMS";
export const CREATE_JOBITEMSSUCCESS = "dashboard/CREATE_JOBITEMSSUCCESS";
